USE [master]
GO

if exists (select * from sys.databases where name = N'MaceWescottHotelData')
begin
	EXEC msdb.dbo.sp_delete_database_backuphistory @database_name = N'MaceWescottHotelData';
	ALTER DATABASE MaceWescottHotelData SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE MaceWescottHotelData;
end

CREATE DATABASE MaceWescottHotelData
GO

USE MaceWescottHotelData
GO

CREATE TABLE GUESTS (
	GuestID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	[Address] VARCHAR(256) NOT NULL,
	City VARCHAR(100) NOT NULL,
	StateAbbr CHAR(2) NOT NULL,
	PostalCode VARCHAR(10) NOT NULL,
	Phone VARCHAR(14) NOT NULL
)

CREATE TABLE AMENITY (
	AmenityID INT IDENTITY(1,1) PRIMARY KEY,
	Amenity CHAR(100) NOT NULL
)

CREATE TABLE ROOMTYPE (
	RoomTypeID INT IDENTITY(1,1) PRIMARY KEY,
	RoomType CHAR(100) NOT NULL
)

CREATE TABLE ROOMS (
	RoomID INT IDENTITY(1,1) PRIMARY KEY,
	RoomNumber CHAR(3) NOT NULL,
	RoomTypeID INT NOT NULL,
	ADA BIT NOT NULL,
	StandardOccupancy INT NOT NULL,
	MaximumOccupancy INT NOT NULL,
	BasePrice DECIMAL(7,2) NOT NULL,
	ExtraPerson DECIMAL(2,0) NULL
	CONSTRAINT fk_ROOMTYPE_RoomTypeID FOREIGN KEY (RoomTypeID)
        REFERENCES ROOMTYPE(RoomTypeID),
)

CREATE TABLE ROOM_AMENITY (
	RoomID INT NOT NULL,
	AmenityID INT NOT NULL
	CONSTRAINT pk_RoomAmenityID PRIMARY KEY (RoomID, AmenityID),
	CONSTRAINT fk_ROOMID FOREIGN KEY (RoomID)
        REFERENCES ROOMS(RoomID),
	CONSTRAINT fk_AMENITY_AmenityID FOREIGN KEY (AmenityID)
        REFERENCES AMENITY(AmenityID)
)

CREATE TABLE GUEST_RESERVATION (
	GuestReservationID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	GuestID UNIQUEIDENTIFIER NOT NULL,
	StartDate DATE NOT NULL,
	EndDate DATE NOT NULL,
	CONSTRAINT fk_GUESTS_GuestID FOREIGN KEY (GuestID)
        REFERENCES GUESTS(GuestID),
)

CREATE TABLE ROOM_RESERVATIONS (
	RoomReservationID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	GuestReservationID UNIQUEIDENTIFIER NOT NULL,
	RoomID INT NOT NULL,
	Adults INT NOT NULL,
	Children INT NULL,
	TotalRoomCost DECIMAL(7,2) NOT NULL
	CONSTRAINT fk_GUEST_RESERVATION_GuestReservationID FOREIGN KEY (GuestReservationID)
        REFERENCES GUEST_RESERVATION(GuestReservationID),
	CONSTRAINT fk_ROOMS_RoomID FOREIGN KEY (RoomID)
        REFERENCES ROOMS(RoomID),
)
